services:
  keycloak_mariadb:
    container_name: keycloak_mariadb
    image: bitnami/mariadb:latest
    ports:
      - 33306:3306
    volumes:
      - /data/keycloak-data:/bitnami/mariadb
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_HOST=localhost
      - MARIADB_PORT=3306
      - MARIADB_DATABASE=keycloak_db
      - MARIADB_USER=keycloak
      - MARIADB_PASSWORD=keycloak
      - MARIADB_ENABLE_SLOW_QUERY
      - MARIADB_LONG_QUERY_TIME=10
      - TZ=Asia/Seoul
    restart: always
    networks:
      - keycloak-net

  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:26.1.3
#   image: my-keycloak:26.1.3-custom
    restart: always
    ports:
      - 30000:8443
#     - 30000:8080
    volumes:
      - ./ssl:/opt/keycloak/ssl
      - ./themes/keycloak-theme-nwc-custom:/opt/keycloak/themes/keycloak-theme-nwc-custom
    command:
      - start
      - --https-certificate-file=/opt/keycloak/ssl/fullchain.pem
      - --https-certificate-key-file=/opt/keycloak/ssl/privkey.pem
      - --hostname=www.kingkongapps.kr
      - --db=mariadb
      - --db-url=jdbc:mariadb://keycloak_mariadb:3306/keycloak_db?characterEncoding=UTF-8
      - --db-schema=keycloak_db
      - --db-username=keycloak
      - --db-password=keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=kingkongapps
      - KC_LOG_LEVEL=DEBUG
      - JAVA_OPTS_APPEND="-Dorg.jboss.logging.provider=slf4j -Dorg.keycloak=DEBUG -Dcom.yourpackage=DEBUG"

    depends_on:
      - keycloak_mariadb
    networks:
      - keycloak-net

networks:
  keycloak-net:
    driver: bridge

